### ISSUE TITLE
Повышение эффективности команд без глюкозы и KPI (Евгений Бриченко)

### ISSUE THREAD

**Issue by aikikode** [deeprefactoring/deeprefactoring.github.io#105]
### Тема доклада 
Повышение эффективности команд без глюкозы и KPI

### Краткое описание
Речь пойдет о климате команды,  интеллектуальном ресурсе и как им управлять без манипуляций

### Докладчик
Евгений Бриченко

**Comment by khorpy** [comment]
Докладчик слился в третий раз
