### ISSUE TITLE
Про.Quality

### ISSUE THREAD

**Issue by Mehonoshin** [deeprefactoring/deeprefactoring.github.io#111]
### Тема доклада 

Про.Quality

### Краткое описание

Тезисы из жизненного опыта и опыта полученного при работе над проектом Bootcamp.
Расскажу свое видение организации процессов разработки в команде/компании, чтобы всем жилось лучше.

### Докладчик

Stanislav Mekhonoshin

**Comment by aikikode** [comment]
https://youtu.be/HfxVJEk2Y48
