### ISSUE TITLE
Сессия вопросов и ответов от бывалых (Евгений Рыжков)

### ISSUE THREAD

**Issue by ykhrustalev** [deeprefactoring/deeprefactoring.github.io#14]
Манипуляция и способы протолкнуть идею

**UPD**: Видео выступления на [YouTube](https://youtu.be/S2i4yP4l0tU)

**Comment by eryzhkov** [comment]
Мне сказали, что накопились некие вопросы по конкретным темам. Т.к. тем может быть много, я предложил устроить именно сессию вопросов и ответов. Возможно, смогу ответить сразу. Возможно, набредем на интересную тему, которую раскрою позже...

**Comment by Pe4enable** [comment]
Как манипулировать разработчиками, как этому противостоять. Как обвинить разработчика в своих просчетах, чтобы он в это поверил.

**Comment by eryzhkov** [comment]
Слишком много для одной сессии )))).

**Comment by eryzhkov** [comment]
можно закрывать?
