### ISSUE TITLE
Гипотеза Сепира — Уорфа и VB.Net (Михаил Аксенов)

### ISSUE THREAD

**Issue by xeningem** [deeprefactoring/deeprefactoring.github.io#45]
### Тема доклада 
Гипотеза Сепира — Уорфа и VB.Net

### Краткое описание
С одной стороны - VB.Net это как C#, разве что немного синтаксис отличается, правда? Правда, но не вся. Рассказ про то, как особенности синтаксиса и исторического наследия мешают программистам писать (хороший?) код и как с этим влиянием можно бороться.

### Докладчик
Михаил Аксенов

### Пару слов о докладчике (если выступает впервые)
.Net разработчик с парой лет стажа

### Контактная информация для публичного доступа (если выступает впервые)
twitter: xeningem

**Comment by Mehonoshin** [comment]
Пора закрыть тикет
