### ISSUE TITLE
Поиск идеи для логотипа

### ISSUE THREAD

**Issue by khorpy** [deeprefactoring/deeprefactoring.github.io#48]
Модное креативное сообщество, объединяющее лучших ИТ-специалистов города Воронеж “Глубокий Рефакторинг”* ищет себе идеи для логотипа. Он будет размещён на сайте, в социальных сетях, на футболках, кружках, бывших домах отдыха и других предметах. Мы обращаемся ко всем неравнодушным с просьбой помочь в поиске идей. Подойдут любые наброски: от карандашных до выполненных в профессиональных редакторах. Требования простые: оригинальная идея, не нарушать социальные нормы и не оскорблять какие-либо группы (можно прогуляться в майке с логотипом по улице). Главное — творческий подход, смелость и наличие смысла. Автору гарантирована слава и пожизненное размещение на доске почёта. Предложения принимаются до 9 мая включительно. Эскизы принимаются в комментриях к [issue](https://github.com/deeprefactoring/deeprefactoring.github.io/issues/48), и в любом другом месте где мы их сможем посмотреть и оценить.

/   * немного иронии

**Comment by aikikode** [comment]
> Сообщество “Глубокий Рефакторинг” ищет себе новый логотип. Он будет размещен на сайте, в социальных сетях, на футболках, кружках и сувенирах.
> 
> Мы обращаемся ко всем неравнодушным с просьбой помочь в поиске идей. Подойдут любые наброски от карандашных до выполненных в редакторах.
> 
> Автору гарантирована слава и пожизненное размещение на доске почёта.

**Comment by igrishaev** [comment]
Коллеги!

Мы ищем идеи для нового логотипа. Старый нас не устраивает, потому что взят из интернета и не отвечает духу сообщества.

Мы обращаемся ко всем неравнодушным с просьбой помочь в поисках. Подойдут любые наброски от карандашных до выполненных в редакторах.

Присылайте ваши идеи до следующего вторника. Прикрепите файл в комментариях к этом ишью. Пожалуйста, воздержитесь от оскорблений и спама. 

Логотип будет размещен на сайте, в социальных сетях, на футболках, кружках и сувенирах. Автору гарантирована слава и упоминание на сайте.

**Comment by samdark** [comment]
![18238894_10213087448001295_8927350301196285443_o](https://cloud.githubusercontent.com/assets/47294/25624321/a9b78ebe-2f61-11e7-8023-73a51971cd56.jpg)
