### ISSUE TITLE
Kubernetes: как деплоить по-царски, попивая смуззи у себя в коворкинге (Роман Гребенников)

### ISSUE THREAD

**Issue by shuttie** [deeprefactoring/deeprefactoring.github.io#5]
* чем вас голый докер не устроил?
* что не так со swarm?
* основы k8s для чайников: Pods, Services, ReplicaSets
* лайв-сессия: заворачиваем простое RESTful приложение в k8s
* k8s для любителей жесткого: PersistentVolume, Claims, StatefulSets
* лайв-сессия: прикручиваем MySQL к нашему приложению из прошлого примера
* внутренняя сеть: overlay networks, weave
* советы бывалых: личный опыт после полугода в проде

(к февралю с докладом не успею, если чо. только на март)

**Comment by khorpy** [comment]
А это один доклад или несколько?

**Comment by shuttie** [comment]
Один, минут на 50. Я умею говорить по-делу и без воды.

**Comment by startxiot** [comment]
Будет интересно, если будет раскрыта тема кластеризации данных и особенности построения/работы сети в кластере. Про работу вычислительной части и "голых" приложений многое написано-сказано, но без учета остального это не так полезно на практике.

**Comment by ykhrustalev** [comment]
https://www.youtube.com/watch?v=TFj-w2-ISVg&
