### ISSUE TITLE
OpenSource изнутри (Александр Макаров)

### ISSUE THREAD

**Issue by samdark** [deeprefactoring/deeprefactoring.github.io#7]
Уже почти 8 лет я занимаюсь [OpenSource PHP фреймворком Yii](http://www.yiiframework.com/) и OpenSource в целом. Пора рассказать, как оно работает изнутри, почему OpenSource — это круто и почему это ужасно.

**Comment by khusnetdinov** [comment]
Было бы интересно узнать про спонсорство в опенсорсе и как оно работает.

**Comment by samdark** [comment]
Никак :)

**Comment by Mehonoshin** [comment]
пора закрыть тикет )
